### ISSUE TITLE
Random "/lib64/ld-linux-x86-64.so.2: No such file or directory" failures when running Maven builds

### ISSUE THREAD

**Issue by chriskilding** [jenkins-infra/packer-images#87] opened 2021-09-09 14:18 UTC
Builds are sometimes failing with this error:

```
09:24:05  + mvn --batch-mode --show-version --errors --no-transfer-progress --update-snapshots -Dmaven.repo.local=/home/jenkins/workspace/edentials-provider-plugin_PR-123@tmp/m2repo -Dmaven.test.failure.ignore -Dspotbugs.failOnError=false -Dcheckstyle.failOnViolation=false -Dcheckstyle.failsOnError=false -Penable-jacoco -Dset.changelist help:evaluate -Dexpression=changelist -Doutput=/home/jenkins/workspace/edentials-provider-plugin_PR-123@tmp/changelist clean install
09:24:05  /lib64/ld-linux-x86-64.so.2: No such file or directory
```

Examples:

- https://ci.jenkins.io/job/Plugins/job/aws-secrets-manager-credentials-provider-plugin/view/change-requests/job/PR-123/1/
- https://ci.jenkins.io/job/Plugins/job/aws-secrets-manager-secret-source-plugin/job/PR-9/3/console
- https://ci.jenkins.io/job/Plugins/job/aws-secrets-manager-credentials-provider-plugin/job/PR-96/13/console
- https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Faws-secrets-manager-credentials-provider-plugin/detail/PR-96/15/pipeline

**Comment by MarkEWaite** [comment] 2021-09-09 14:23
I believe that the root cause of the issue is either that the ARM64 agent doesn't already have Java 11 installed (which it should) or the global tool configuration on ci.jenkins.io is not configured to know that it is installed or it is incorrectly configured to install the AMD64 Java 11 on a machine that needs the Arm64 Java 11.

See the [job log line](https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Faws-secrets-manager-credentials-provider-plugin/detail/PR-96/15/pipeline#step-82-log-1) where it says:

```
Unpacking https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.12+7/OpenJDK11U-jdk_x64_linux_hotspot_11.0.12_7.tar.gz to /home/jenkins/tools/hudson.model.JDK/jdk11 on EC2 (aws) - ARM64 ubuntu 20.04
```

Notice that it is unpacking an "x64" tar file on an ARM64 agent.  It should either not be unpacking anything (if Java 11 is already available) or should be unpacking the Arm64 Java 11 if Java 11 is not already installed on that image

**Comment by chriskilding** [comment] 2021-09-09 14:33
Interesting... didn't know we were routinely running plugin builds on ARM agents? (Is this a cost saving thing?)

**Comment by MarkEWaite** [comment] 2021-09-09 14:34
I think it is more likely an accident of some other configuration error, but it should work.  ARM agents have been working for me for about 6 months and have been available on ci.jenkins.io for at least that long, though not included in the usual labels

**Comment by timja** [comment] 2021-09-09 15:03
I assume it's because of:
![image](https://user-images.githubusercontent.com/21194782/132711261-bb2bb7ff-f9e9-435c-93fa-08bc15e6bfe6.png)

we just request linux.

you can pin to amd64 with:

```
linux && amd64
```

(obviously this should be fixed, from a quick look I haven't found the misconfiguration)

**Comment by timja** [comment] 2021-09-09 15:50
don't forget to update the code, that will get overridden

**Comment by MarkEWaite** [comment] 2021-09-09 15:53
> don't forget to update the code, that will get overridden

Thanks.  I'll check that later today.  I thought that we were only managing agent configuration with JCasC on ci.jenkins.io, not global tool configuration.

**Comment by timja** [comment] 2021-09-09 16:02
nope tools were done first

**Comment by MarkEWaite** [comment] 2021-09-10 02:28
https://github.com/jenkins-infra/jenkins-infra/pull/1856 is the pull request

**Closed by MarkEWaite** 2021-09-10 02:28 UTC
